<a href="https://colab.research.google.com/github/b191243/resume/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [3]:
print(a[0,1])
b[0,0]=77
print(a[0,1])

2
77


In [5]:
a=np.array([[1,2,3], [4,5,6], [7,8,9],[10,11,12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


IndexError: ignored