<a href="https://colab.research.google.com/github/b191243/resume/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a= np.array([1,2,3])
print(type(a), a.shape, a[0], a[1], a[2])
a[0] =5
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [ ]:
b =np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(b.shape)
print(b[0,0], b[0,1], b[1,0])

(2, 3)
1 2 4


In [ ]:
a=np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [ ]:
b=np.ones((1,2))
print(b)

[[1. 1.]]


In [ ]:
c=np.full((2,2),7)
print(c)

[[7 7]
 [7 7]]


In [ ]:
d=np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]
